Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: 'Information'
      Microsoft.AspNetCore.Hosting.Diagnostics: 'Debug'
      Microsoft.Hosting.Lifetime": 'Debug'
      System": 'Information'
