Serilog:
  MinimumLevel:
    Default: 'Information'
    Override:
      Microsoft: 'Warning'
      Microsoft.AspNetCore.Hosting.Diagnostics: 'Information'
      Microsoft.Hosting.Lifetime: 'Information'
      System: 'Warning'
AllowedHosts: '*'
Metrics:
  Enabled: true
  Tracking:
    ApdexTrackingEnabled: true
    ApdexTSeconds: 0.1
    IgnoredHttpStatusCodes: [404]
    IgnoredRoutesRegexPatterns: []
    OAuth2TrackingEnabled: true
