Serilog:
  MinimumLevel:
    Default: 'Information'
    Override:
      Microsoft: 'Warning'
      Microsoft.AspNetCore.Hosting.Diagnostics: 'Information'
      Microsoft.Hosting.Lifetime: 'Information'
      System: 'Warning'
Metrics:
  Enabled: true
