Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
AllowedHosts: '*'
Metrics:
  Enabled: true
  Tracking:
    ApdexTrackingEnabled: true
    ApdexTSeconds: 0.1
    IgnoredHttpStatusCodes: [ 404 ]
    IgnoredRoutesRegexPatterns: []
    OAuth2TrackingEnabled: true
